spring.application.name=api-gateway

server.port=4000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# must match auth-service and UserInfo exactly
jwt.secret=ThisIsADemoSecretKeyPleaseChangeIt32Bytes!
jwt.expiration-ms=3600000
